### ISSUE TITLE
SimplyStatus v1.7.1 not working on Quilt (23w13a_or_b)

### ISSUE THREAD

**Issue by noobnarb** [simply-kel/SimplyStatus#9]
Your mod says it supports it but the error says I need fabric...

LOGS
https://pastebin.com/yPmpELbd

**Comment by simply-kel** [comment]
It most likely requires the "Quilted Fabric API", there is no such version on Modrinth. 
So most likely Quilt will not work on 23w13a_or_b, I remember there is one for this version Fabric API
